services:
  - type: web
    name: hedera-ramp-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: hedera-ramp-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: HEDERA_NETWORK
        value: testnet
      - key: CORS_ORIGINS
        value: https://hedera-ramp.vercel.app,https://hedera-ramp.vercel.app
      - key: MPESA_CONSUMER_KEY
        value: your_mpesa_consumer_key
      - key: MPESA_CONSUMER_SECRET
        value: your_mpesa_consumer_secret
      - key: MPESA_SHORTCODE
        value: your_mpesa_shortcode
      - key: MPESA_PASSKEY
        value: your_mpesa_passkey

databases:
  - name: hedera-ramp-db
    plan: free
    databaseName: hedera_ramp
    user: hedera_ramp_user
